nvidia:
  compiler:
    - toolchain: gcc
      spec: gcc
    - toolchain: llvm
      spec: nvhpc
  unify: true
  mpi:
    spec: cray-mpich@8.1.30%nvhpc
    gpu: cuda
  specs:
    - boost ~mpi
    - python@3.10
    - eccodes@2.25.0%nvhpc +tools +fortran +aec +openmp jp2k=jasper
    - cmake%gcc
    - cuda@12.3%gcc
    - openblas%gcc
    - hwloc%gcc
    - hdf5%nvhpc +hl
    - netcdf-c
    - netcdf-cxx4
    - netcdf-fortran%nvhpc
    - numactl
    - osu-micro-benchmarks@5.9%nvhpc
    # everything needed for nccl on SS11
    - aws-ofi-nccl@master
    - nccl
    - nccl-tests
  variants:
    - cuda_arch=80
    - +mpi
    - +cuda
  packages:
    - curl
    - gmake
    - perl
  views:
    icon:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
